[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/inventory/view"
  to = "/inventory/view.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
